version: '3.4'
#cli: docker-compose -f docker-compose.debug.yml run --rm zero-test node index.js --help
services:
  zero-test:
    image: zero-test
    build:
      context: .
    environment:
      NODE_ENV: development
    volumes: 
      - ../index.js:/usr/src/app/index.js
    # command: ["node", "index.js", "--help"]
